### ISSUE TITLE
Provide Docker Runtime

### ISSUE THREAD

**Issue by mjallday** [verygoodsecurity/starlarky#140]
It would be good to have a dockerized container that allows executing starlark runtime locally.

This would be useful for local development as well as running other projects such as argo workflows. 

Here's an example of how it could be used in argo

```yaml
script:
   image: starlarky:1.0
   command:
   - python
   source: |
      load("@stdlib//re2j", "re2j")
      def process(input, ctx):
         # do your code here
```

I guess the concept here is that we'd provide an entrypoint or cmd which takes a script as an input and then allows it to be invoked by passing data via stdin/stdout. 

I'm not sure exactly how the api would work but it would be useful for executing starlarky anywhere.
